### ISSUE TITLE
Cannot set default database name for RethinkDB

### ISSUE THREAD

**Issue by nfsmaniac** [deepstreamIO/deepstream.io-storage-rethinkdb#24]
I am using Deepstream.io v5.0.4 binary for Linux.
My configuration file (config.yml) looks like this
```
storage:
  name: rethinkdb
  options:

    host: localhost
    port: 28015

    database: mydatabase
    defaultTable: mytable

    splitChar: /
```

It's default config + copy & pasted config from Deepstream docs of the RethinkDB connector at the end of file.
First, I realised the [docs](https://deepstream.io/tutorials/plugins/database/rethinkdb/) are outdated. There is `path: rethinkdb`, but I had to change it to `name: rethinkdb`.

But the main problem is -- I can't set default DB name to `mydatabase`. When deepestream server is launched, it always creates a new database called `deepstream` and creates a table called `mytable`.

Is there any syntax change for the `database:` option, as same as for `path:` -> `name:`?

**Comment by ehrenb** [comment]
Hello - I'm having a similar issue, it appears that the RethinkDB plugin's option name changed from 'database' to 'db'.  

See RethinkDBOptions in: 
* https://github.com/deepstreamIO/deepstream.io-storage-rethinkdb/blob/master/src/connector.ts 

and the test case:
* https://github.com/deepstreamIO/deepstream.io-storage-rethinkdb/blob/9a793c24bee96c23153aa3e28722f039ada4215d/test/connection-params.ts

Switching 'database' to 'db' makes my custom named database, but I'm unable to get the custom table created through the 'defaultTable' option.  My config is below:

```yml
plugins:
  storage:
    name: rethinkdb
    options:
      host: rethinkdb
      port: 28015
      db: 'mydb'
      defaultTable: 'leads'
      splitChar: '/'
```
